//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/modified/UVCAST/messages/BeaconMessage.msg.
//

#ifndef __VEINS_BEACONMESSAGE_M_H
#define __VEINS_BEACONMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/modified/UVCAST/messages/BeaconMessage.msg:17</tt> by nedtool.
 * <pre>
 * packet BeaconMessage
 * {
 *     int receivedMessages[];
 * }
 * </pre>
 */
class VEINS_API BeaconMessage : public ::omnetpp::cPacket
{
  protected:
    int *receivedMessages; // array ptr
    unsigned int receivedMessages_arraysize;

  private:
    void copy(const BeaconMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const BeaconMessage&);

  public:
    BeaconMessage(const char *name=nullptr, short kind=0);
    BeaconMessage(const BeaconMessage& other);
    virtual ~BeaconMessage();
    BeaconMessage& operator=(const BeaconMessage& other);
    virtual BeaconMessage *dup() const override {return new BeaconMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setReceivedMessagesArraySize(unsigned int size);
    virtual unsigned int getReceivedMessagesArraySize() const;
    virtual int getReceivedMessages(unsigned int k) const;
    virtual void setReceivedMessages(unsigned int k, int receivedMessages);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const BeaconMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, BeaconMessage& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_BEACONMESSAGE_M_H

