//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/modified/P2PCongestionAvoidance/Messages/CongestionResponse.msg.
//

#ifndef __VEINS_CONGESTIONRESPONSE_M_H
#define __VEINS_CONGESTIONRESPONSE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/modules/messages/BaseFrame1609_4_m.h"
#include "CongestionInfoStruct_m.h"
#include <vector>
typedef std::vector<veins::CongestionInfoStruct> cInfoVector;
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/modified/P2PCongestionAvoidance/Messages/CongestionResponse.msg:29</tt> by nedtool.
 * <pre>
 * packet CongestionResponse extends BaseFrame1609_4
 * {
 *     // An array of CongestionInfoStruct
 *     cInfoVector cInfoStructDB;
 * }
 * </pre>
 */
class VEINS_API CongestionResponse : public ::veins::BaseFrame1609_4
{
  protected:
    cInfoVector cInfoStructDB;

  private:
    void copy(const CongestionResponse& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CongestionResponse&);

  public:
    CongestionResponse();
    CongestionResponse(const CongestionResponse& other);
    virtual ~CongestionResponse();
    CongestionResponse& operator=(const CongestionResponse& other);
    virtual CongestionResponse *dup() const override {return new CongestionResponse(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual cInfoVector& getCInfoStructDB();
    virtual const cInfoVector& getCInfoStructDB() const {return const_cast<CongestionResponse*>(this)->getCInfoStructDB();}
    virtual void setCInfoStructDB(const cInfoVector& cInfoStructDB);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CongestionResponse& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CongestionResponse& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_CONGESTIONRESPONSE_M_H

