//
// Generated file, do not edit! Created by nedtool 5.6 from veins/modules/application/traci/modified/P2PCongestionAvoidance/Messages/CongestionRequest.msg.
//

#ifndef __VEINS_CONGESTIONREQUEST_M_H
#define __VEINS_CONGESTIONREQUEST_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif

// dll export symbol
#ifndef VEINS_API
#  if defined(VEINS_EXPORT)
#    define VEINS_API  OPP_DLLEXPORT
#  elif defined(VEINS_IMPORT)
#    define VEINS_API  OPP_DLLIMPORT
#  else
#    define VEINS_API
#  endif
#endif

// cplusplus {{
#include "veins/modules/messages/BaseFrame1609_4_m.h"
typedef std::string cppString;
// }}


namespace veins {

/**
 * Class generated from <tt>veins/modules/application/traci/modified/P2PCongestionAvoidance/Messages/CongestionRequest.msg:25</tt> by nedtool.
 * <pre>
 * packet CongestionRequest extends BaseFrame1609_4
 * {
 *     // Query about the next set of candidate roads
 *     cppString roadsOfInterest[];
 * }
 * </pre>
 */
class VEINS_API CongestionRequest : public ::veins::BaseFrame1609_4
{
  protected:
    cppString *roadsOfInterest; // array ptr
    unsigned int roadsOfInterest_arraysize;

  private:
    void copy(const CongestionRequest& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CongestionRequest&);

  public:
    CongestionRequest(const char *name=nullptr, short kind=0);
    CongestionRequest(const CongestionRequest& other);
    virtual ~CongestionRequest();
    CongestionRequest& operator=(const CongestionRequest& other);
    virtual CongestionRequest *dup() const override {return new CongestionRequest(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual void setRoadsOfInterestArraySize(unsigned int size);
    virtual unsigned int getRoadsOfInterestArraySize() const;
    virtual cppString& getRoadsOfInterest(unsigned int k);
    virtual const cppString& getRoadsOfInterest(unsigned int k) const {return const_cast<CongestionRequest*>(this)->getRoadsOfInterest(k);}
    virtual void setRoadsOfInterest(unsigned int k, const cppString& roadsOfInterest);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CongestionRequest& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CongestionRequest& obj) {obj.parsimUnpack(b);}

} // namespace veins

#endif // ifndef __VEINS_CONGESTIONREQUEST_M_H

